// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type Equipo struct {
	IDEquipo      int32  `json:"id_equipo"`
	NombreEquipo  string `json:"nombre_equipo"`
	CantJugadores int32  `json:"cant_jugadores"`
	Division      string `json:"division"`
}
