// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createEquipo = `-- name: CreateEquipo :one

INSERT INTO equipo (nombre_equipo, division)
VALUES ($1, $2)
RETURNING id_equipo, nombre_equipo, division
`

type CreateEquipoParams struct {
	NombreEquipo string `json:"nombre_equipo"`
	Division     string `json:"division"`
}

// =========================
// EQUIPO
// =========================
func (q *Queries) CreateEquipo(ctx context.Context, arg CreateEquipoParams) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, createEquipo, arg.NombreEquipo, arg.Division)
	var i Equipo
	err := row.Scan(&i.IDEquipo, &i.NombreEquipo, &i.Division)
	return i, err
}

const createJugador = `-- name: CreateJugador :one

INSERT INTO jugador (nombre, apellido, id_equipo)
VALUES ($1, $2, $3)
RETURNING id_jugador, nombre, apellido, id_equipo
`

type CreateJugadorParams struct {
	Nombre   string `json:"nombre"`
	Apellido string `json:"apellido"`
	IDEquipo int32  `json:"id_equipo"`
}

// =========================
// JUGADOR
// =========================
func (q *Queries) CreateJugador(ctx context.Context, arg CreateJugadorParams) (Jugador, error) {
	row := q.db.QueryRowContext(ctx, createJugador, arg.Nombre, arg.Apellido, arg.IDEquipo)
	var i Jugador
	err := row.Scan(
		&i.IDJugador,
		&i.Nombre,
		&i.Apellido,
		&i.IDEquipo,
	)
	return i, err
}

const createPartido = `-- name: CreatePartido :one

INSERT INTO partido (
    id_equipo_local,
    id_equipo_visitante,
    goles_local,
    goles_visitante,
    fecha
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id_partido, id_equipo_local, id_equipo_visitante, goles_local, goles_visitante, fecha
`

type CreatePartidoParams struct {
	IDEquipoLocal     int32     `json:"id_equipo_local"`
	IDEquipoVisitante int32     `json:"id_equipo_visitante"`
	GolesLocal        int32     `json:"goles_local"`
	GolesVisitante    int32     `json:"goles_visitante"`
	Fecha             time.Time `json:"fecha"`
}

// =========================
// PARTIDO
// =========================
func (q *Queries) CreatePartido(ctx context.Context, arg CreatePartidoParams) (Partido, error) {
	row := q.db.QueryRowContext(ctx, createPartido,
		arg.IDEquipoLocal,
		arg.IDEquipoVisitante,
		arg.GolesLocal,
		arg.GolesVisitante,
		arg.Fecha,
	)
	var i Partido
	err := row.Scan(
		&i.IDPartido,
		&i.IDEquipoLocal,
		&i.IDEquipoVisitante,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Fecha,
	)
	return i, err
}

const deleteEquipo = `-- name: DeleteEquipo :exec
DELETE FROM equipo
WHERE id_equipo = $1
`

func (q *Queries) DeleteEquipo(ctx context.Context, idEquipo int32) error {
	_, err := q.db.ExecContext(ctx, deleteEquipo, idEquipo)
	return err
}

const deleteJugador = `-- name: DeleteJugador :exec
DELETE FROM jugador
WHERE id_jugador = $1
`

func (q *Queries) DeleteJugador(ctx context.Context, idJugador int32) error {
	_, err := q.db.ExecContext(ctx, deleteJugador, idJugador)
	return err
}

const deletePartido = `-- name: DeletePartido :exec
DELETE FROM partido
WHERE id_partido = $1
`

func (q *Queries) DeletePartido(ctx context.Context, idPartido int32) error {
	_, err := q.db.ExecContext(ctx, deletePartido, idPartido)
	return err
}

const getEquipo = `-- name: GetEquipo :one
SELECT id_equipo, nombre_equipo, division
FROM equipo
WHERE id_equipo = $1
`

func (q *Queries) GetEquipo(ctx context.Context, idEquipo int32) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, getEquipo, idEquipo)
	var i Equipo
	err := row.Scan(&i.IDEquipo, &i.NombreEquipo, &i.Division)
	return i, err
}

const getJugador = `-- name: GetJugador :one
SELECT id_jugador, nombre, apellido, id_equipo
FROM jugador
WHERE id_jugador = $1
`

func (q *Queries) GetJugador(ctx context.Context, idJugador int32) (Jugador, error) {
	row := q.db.QueryRowContext(ctx, getJugador, idJugador)
	var i Jugador
	err := row.Scan(
		&i.IDJugador,
		&i.Nombre,
		&i.Apellido,
		&i.IDEquipo,
	)
	return i, err
}

const getPartido = `-- name: GetPartido :one
SELECT id_partido, id_equipo_local, id_equipo_visitante, goles_local, goles_visitante, fecha
FROM partido
WHERE id_partido = $1
`

func (q *Queries) GetPartido(ctx context.Context, idPartido int32) (Partido, error) {
	row := q.db.QueryRowContext(ctx, getPartido, idPartido)
	var i Partido
	err := row.Scan(
		&i.IDPartido,
		&i.IDEquipoLocal,
		&i.IDEquipoVisitante,
		&i.GolesLocal,
		&i.GolesVisitante,
		&i.Fecha,
	)
	return i, err
}

const listEquipos = `-- name: ListEquipos :many
SELECT id_equipo, nombre_equipo, division
FROM equipo
ORDER BY division ASC, nombre_equipo ASC
`

func (q *Queries) ListEquipos(ctx context.Context) ([]Equipo, error) {
	rows, err := q.db.QueryContext(ctx, listEquipos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipo
	for rows.Next() {
		var i Equipo
		if err := rows.Scan(&i.IDEquipo, &i.NombreEquipo, &i.Division); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJugadores = `-- name: ListJugadores :many
SELECT id_jugador, nombre, apellido, id_equipo
FROM jugador
ORDER BY apellido ASC, nombre ASC
`

func (q *Queries) ListJugadores(ctx context.Context) ([]Jugador, error) {
	rows, err := q.db.QueryContext(ctx, listJugadores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Jugador
	for rows.Next() {
		var i Jugador
		if err := rows.Scan(
			&i.IDJugador,
			&i.Nombre,
			&i.Apellido,
			&i.IDEquipo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartidos = `-- name: ListPartidos :many
SELECT id_partido, id_equipo_local, id_equipo_visitante, goles_local, goles_visitante, fecha
FROM partido
ORDER BY fecha ASC
`

func (q *Queries) ListPartidos(ctx context.Context) ([]Partido, error) {
	rows, err := q.db.QueryContext(ctx, listPartidos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Partido
	for rows.Next() {
		var i Partido
		if err := rows.Scan(
			&i.IDPartido,
			&i.IDEquipoLocal,
			&i.IDEquipoVisitante,
			&i.GolesLocal,
			&i.GolesVisitante,
			&i.Fecha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipo = `-- name: UpdateEquipo :exec
UPDATE equipo
SET nombre_equipo = $2,
    division = $3
WHERE id_equipo = $1
`

type UpdateEquipoParams struct {
	IDEquipo     int32  `json:"id_equipo"`
	NombreEquipo string `json:"nombre_equipo"`
	Division     string `json:"division"`
}

func (q *Queries) UpdateEquipo(ctx context.Context, arg UpdateEquipoParams) error {
	_, err := q.db.ExecContext(ctx, updateEquipo, arg.IDEquipo, arg.NombreEquipo, arg.Division)
	return err
}

const updateJugador = `-- name: UpdateJugador :exec
UPDATE jugador
SET nombre = $2,
    apellido = $3,
    id_equipo = $4
WHERE id_jugador = $1
`

type UpdateJugadorParams struct {
	IDJugador int32  `json:"id_jugador"`
	Nombre    string `json:"nombre"`
	Apellido  string `json:"apellido"`
	IDEquipo  int32  `json:"id_equipo"`
}

func (q *Queries) UpdateJugador(ctx context.Context, arg UpdateJugadorParams) error {
	_, err := q.db.ExecContext(ctx, updateJugador,
		arg.IDJugador,
		arg.Nombre,
		arg.Apellido,
		arg.IDEquipo,
	)
	return err
}

const updatePartido = `-- name: UpdatePartido :exec
UPDATE partido
SET id_equipo_local = $2,
    id_equipo_visitante = $3,
    goles_local = $4,
    goles_visitante = $5,
    fecha = $6
WHERE id_partido = $1
`

type UpdatePartidoParams struct {
	IDPartido         int32     `json:"id_partido"`
	IDEquipoLocal     int32     `json:"id_equipo_local"`
	IDEquipoVisitante int32     `json:"id_equipo_visitante"`
	GolesLocal        int32     `json:"goles_local"`
	GolesVisitante    int32     `json:"goles_visitante"`
	Fecha             time.Time `json:"fecha"`
}

func (q *Queries) UpdatePartido(ctx context.Context, arg UpdatePartidoParams) error {
	_, err := q.db.ExecContext(ctx, updatePartido,
		arg.IDPartido,
		arg.IDEquipoLocal,
		arg.IDEquipoVisitante,
		arg.GolesLocal,
		arg.GolesVisitante,
		arg.Fecha,
	)
	return err
}
