// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const createEquipo = `-- name: CreateEquipo :one
INSERT INTO equipo (id_equipo, nombre_equipo, cant_jugadores, division) 
VALUES ($1, $2, $3, $4) 
RETURNING id_equipo, nombre_equipo, cant_jugadores, division
`

type CreateEquipoParams struct {
	IDEquipo      int32  `json:"id_equipo"`
	NombreEquipo  string `json:"nombre_equipo"`
	CantJugadores int32  `json:"cant_jugadores"`
	Division      string `json:"division"`
}

func (q *Queries) CreateEquipo(ctx context.Context, arg CreateEquipoParams) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, createEquipo,
		arg.IDEquipo,
		arg.NombreEquipo,
		arg.CantJugadores,
		arg.Division,
	)
	var i Equipo
	err := row.Scan(
		&i.IDEquipo,
		&i.NombreEquipo,
		&i.CantJugadores,
		&i.Division,
	)
	return i, err
}

const deleteEquipo = `-- name: DeleteEquipo :exec
DELETE FROM equipo 
WHERE id_equipo = $1
`

func (q *Queries) DeleteEquipo(ctx context.Context, idEquipo int32) error {
	_, err := q.db.ExecContext(ctx, deleteEquipo, idEquipo)
	return err
}

const getEquipo = `-- name: GetEquipo :one
SELECT id_equipo, nombre_equipo, cant_jugadores, division FROM equipo 
WHERE id_equipo = $1
`

func (q *Queries) GetEquipo(ctx context.Context, idEquipo int32) (Equipo, error) {
	row := q.db.QueryRowContext(ctx, getEquipo, idEquipo)
	var i Equipo
	err := row.Scan(
		&i.IDEquipo,
		&i.NombreEquipo,
		&i.CantJugadores,
		&i.Division,
	)
	return i, err
}

const listEquipos = `-- name: ListEquipos :many
SELECT id_equipo, nombre_equipo, cant_jugadores, division FROM equipo 
ORDER BY division ASC, nombre_equipo ASC
`

func (q *Queries) ListEquipos(ctx context.Context) ([]Equipo, error) {
	rows, err := q.db.QueryContext(ctx, listEquipos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Equipo
	for rows.Next() {
		var i Equipo
		if err := rows.Scan(
			&i.IDEquipo,
			&i.NombreEquipo,
			&i.CantJugadores,
			&i.Division,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEquipo = `-- name: UpdateEquipo :exec
UPDATE equipo 
SET nombre_equipo = $2, cant_jugadores = $3, division = $4 
WHERE id_equipo = $1
`

type UpdateEquipoParams struct {
	IDEquipo      int32  `json:"id_equipo"`
	NombreEquipo  string `json:"nombre_equipo"`
	CantJugadores int32  `json:"cant_jugadores"`
	Division      string `json:"division"`
}

func (q *Queries) UpdateEquipo(ctx context.Context, arg UpdateEquipoParams) error {
	_, err := q.db.ExecContext(ctx, updateEquipo,
		arg.IDEquipo,
		arg.NombreEquipo,
		arg.CantJugadores,
		arg.Division,
	)
	return err
}
